server:
  port: 8090

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: Hearing Recordings Ingestor

ingestion:
  max-number-of-files-to-process-per-batch: ${MAX_NUMBER_OF_FILES_TO_PROCESS_PER_BATCH:12}



azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:true}
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:d04b52b1-20e5-473a-8ac4-3f6859ea113c}
  storage:
    cvp-storage-connection-string: ${CVP_STORAGE_CONNECTION_STRING:DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=https://127.0.0.1:10000/devstoreaccount1}
    cvp-storage-container-name: ${CVP_STORAGE_CONTAINER_NAME:cvptestcontainer}
    enabled: true

s2s.hrs.api:
  url: ${HRS_API_BASE_URI:http://localhost:8080}

clamav:
  host: ${HRS_CLAM_AV_HOST:localhost}
  port: ${HRS_CLAM_AV_PORT:3310}
  timeout: 60000

idam:
  s2s-auth:
    url: ${S2S_BASE_URI:http://localhost:4502}
    totp_secret: ${S2S_KEY:AAAAAAAAAAAAAAAA}
    microservice: em_hrs_ingestor
